### PR TITLE
Add boardName filter param and env var

### PR DESCRIPTION
**Pull request by dotLou**
JIRA's board list API limits (by default) 50 things returned. This PR allows filtering of items using the existing `?name=blah` query parameter that JIRA exposes.

### CODE REVIEW

**Comment by hairyhenderson** [comment]
@dotLou bitHound is whining about some duplicate code: https://www.bithound.io/github/hairyhenderson/jiraprinter/blob/49aea25b32c96834d77a58c57fdeb52048e0f460/test/boards_test.js - I'm not convinced it's a big deal, but I also want the thing to be 💚 😉

**Comment by dotLou** [comment]
@hairyhenderson It's in tests - but I can move that verification to a function within the file and call it if that works?

**Comment by hairyhenderson** [comment]
> JIRA's board list API limits (by default) 50 things returned

I wonder if we should also add paging support? In a follow-up PR, naturally...

**Comment by dotLou** [comment]
@hairyhenderson I think this is ready to go then?

**Comment by hairyhenderson** [comment]
Thanks @dotLou - sorry that took so long!

**Pull request merged**
