### PR TITLE
New Print style for cards

### PR DESCRIPTION
**Pull request by dotLou**
New print style for cards.

This includes:

- Component issue item added (customizable, of course)
- Priority button at top left (assumes first character is number of 1-4 of priority, colours it based on that)
- Bug and Story types at top left
- Points at bottom right
- Component tag at bottom (only shows the first component)
- Standardized CSS (one look for web + print)
- [x] Need to determine default colours for priorities
- [x] Need to determine default colours for issue types

Example cards (browser):

image

Example cards (print):
image
image

### CODE REVIEW

**Comment by dotLou** [comment]
@masaruhoshi Yeah there's still two unchecked things in the list above!

**Comment by hairyhenderson** [comment]
@dotLou Looking good! I'll :+1: this and merge once the outstanding TODOs are resolved.

**Comment by dotLou** [comment]
@hairyhenderson Defaulting to black text on white background for all other cases, this is ready for 👀

**Comment by hairyhenderson** [comment]
> Any thoughts on default colours at all

¯\\\_(ツ)_/¯

This looks good!

**Comment by hairyhenderson** [comment]
@dotLou thanks for this - looking good and I like the fact that it's the same across web/css!

As a follow-up can you update https://github.com/hairyhenderson/jiraprinter/blob/master/sample_card.png to reflect the new style? Just so the README isn't confusing 😉

**Pull request merged**
